#!/bin/bash
# FREEFY
# A simple script to add a header to a file 
# Use: freefy foo bar - adds GPL version 3 header with the program name set to 'foo' and program author set to 'bar' to all files in current directory and copies the full license file to the current directory

# Set default variables
license=GPLv3
header=./licenses/$license-header.txt #DEBUG: change for release
year=(`date +%Y`)

installed_directory=/home/imperium/Desktop/freefy     #DEBUG: change for release

# Set error codes
E_NOARGS=85

# Check command line options
while getopts "hpy:l:" opt; do
  case $opt in
  h)
    cat $installed_directory/licenses/README
    exit 0
  ;;
  p)
    ls $installed_directory/licenses/ 
    exit 0
  ;;
  y)
    year=$OPTARG
  ;;
  l)
    license=$OPTARG
  ;;
  \?)
    echo "Unknown option" >&2 
    exit 1
  ;;
  esac
done

echo "OPTIND = $OPTIND " 
shift {$OPTIND-1}

# Check for required arguments
if [ -z "$1" && -z $2]; then		# The first argument $1 is the name of the program, second is the program author
	echo "freefy:missing file operand";
	exit $E_NOARGS;
fi

# Get the list of files in the current directory and its length
file_list=(`ls`)
file_list_length=${#file_list[*]}

echo "length = $file_list_length" #DEBUG
echo "year = $year" #DEBUG
echo "license = $license" #DEBUG
echo "program name = $1"
echo "program author = $2"

# Concatenate a header at the top of each file in the list (excluding directories, links, etc.)
i=0
while [ $i -lt $file_list_length ]; do
	if [ -f ${file_list[$i]} ]; then
	echo "File $i: ${file_list[$i]}" #DEBUG
	cat $header ${file_list[$i]} > temp
	mv temp ${file_list[$i]}
	sed -i 's/<program>/'$1'/g;s/<author>/'$2'/g;s/<year>/'$year'/g' ${file_list[$i]}
	fi
let i++
done

# Copy license file to current directory
cp $installed_directory/licenses/$license.txt ./LICENSE

# Exit OK
exit 0
