#!/bin/bash
# FREEFY
# A simple script to add a header to a file 
# Use: freefy foo bar - adds GPL version 3 header with the program name set to 'foo' and program author set to 'bar' to all files in current directory and copies the full license file to the current directory

# Set default variables
license=GPLv3
year=(`date +%Y`)
installed_directory=/usr/share/freefy

# Set error codes
E_NOARGS=85
E_OK=0
E_ERROR=1

# Check command line options
while getopts ":hpy:l:" opt; do
  case $opt in
  h)
    cat $installed_directory/README          
    exit $E_OK
  ;;
  p)
    cat $installed_directory/LIST
    exit $E_OK
  ;;
  y)
    year=$OPTARG
  ;;
  l)
    license=$OPTARG
  ;;
  \?)
    echo "Unknown option. Try 'freefy -h' for more information." >&2 
    exit $E_ERROR
  ;;
  esac
done

# Shift the command line marker by some positions, evaluated by processed options by getopts - 1
shift $(($OPTIND-1))

# Check for required arguments
if [ -z "$1" ] || [ -z "$2" ] ; then		# The first argument $1 is the name of the program, second is the program author
	echo "freefy:missing file operand"  >&2;
	exit $E_NOARGS;
fi

echo "Program name will be set to: $1"    
echo "Program author will be set to: $2"  

# Get the list of files in the current directory and its length
file_list=(`ls`)
file_list_length=${#file_list[*]}

# Get header for specifyed license
header=$installed_directory/licenses/$license-header.txt 

# Concatenate a header at the top of each file in the list (excluding directories, links, etc.)
i=0
while [ $i -lt $file_list_length ]; do
  if [ -f ${file_list[$i]} ]; then
  cat $header ${file_list[$i]} > temp
  mv temp ${file_list[$i]}
  sed -i 's/<program>/'$1'/g;s/<author>/'$2'/g;s/<year>/'$year'/g' ${file_list[$i]}
  fi
let i++
done

# Copy license file to current directory
cp $installed_directory/licenses/$license.txt ./LICENSE

# Exit OK
exit $E_OK
